version: "3.9"

services:
    composer:
        image: composer
        command: install
        volumes:
            - ./wordpress:/app

    db:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - ./wordpress:/var/www/html
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

    wp-cli:
        image: wordpress:cli
        depends_on:
            - db
            - wordpress
        volumes:
            - ./wait-for-mysql.sh:/wait-for-mysql.sh
            - ./wordpress:/var/www/html
        command: /wait-for-mysql.sh
        user: xfs
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
